// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_AEm3UiTcy95XzPIb_04J1EUsDnFdCyU',
    appId: '1:549230556174:web:9a3ac15be32721a7d0f85f',
    messagingSenderId: '549230556174',
    projectId: 'phoneauth-firebase-ed49c',
    authDomain: 'phoneauth-firebase-ed49c.firebaseapp.com',
    databaseURL: 'https://phoneauth-firebase-ed49c-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-firebase-ed49c.appspot.com',
    measurementId: 'G-N4YZL4KCT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0LaM6liT-javuiImlZaYhjBfcWWQqsk',
    appId: '1:549230556174:android:6a90d531bb176d91d0f85f',
    messagingSenderId: '549230556174',
    projectId: 'phoneauth-firebase-ed49c',
    databaseURL: 'https://phoneauth-firebase-ed49c-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-firebase-ed49c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqa0xwTdXFsIrXFH-JLe_ZaHmZjVZr99U',
    appId: '1:549230556174:ios:b9dff7f59ecbb635d0f85f',
    messagingSenderId: '549230556174',
    projectId: 'phoneauth-firebase-ed49c',
    databaseURL: 'https://phoneauth-firebase-ed49c-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-firebase-ed49c.appspot.com',
    androidClientId: '549230556174-tg7d325encrnve5j38e4mgfkul6kmc58.apps.googleusercontent.com',
    iosClientId: '549230556174-jm1m63evocfa3qi2lqsefmrenh69lnre.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauthFirebase',
  );
}
